FROM node:18 as BUILD

WORKDIR usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build


FROM node:18-alpine

WORKDIR usr/src/app

COPY --from=BUILD /usr/src/app/dist ./dist
COPY --from=BUILD /usr/src/app/node_modules ./node_modules
COPY --from=BUILD /usr/src/app/ ./node_modules


EXPOSE 8888

CMD [ "node", "dist/main" ]